server:
  port: 80
  servlet:
    context-path: /is

spring:
  thymeleaf:
    #前缀，也就是模板存放的路径
    prefix: classpath:/templates/
    #编码格式
    encoding: UTF-8
    check-template-location: false
    #关闭缓存，不然无法看到实时页面
    cache: false
    #后缀
    suffix: .html
    #设置不严格的html
    mode: HTML
    servlet:
      content-type: text/html

  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息:初始化大小，最小，最大
    initial-size: 8
    min-idle: 1
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    #验证库是否正常sql
    validation-query: select 'x' from dual
    #空闲时验证，防止连接断开
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    use-global-data-source-stat: true

#MyBatisPlus相关配置
mybatis-plus:
  #mapper映射文件位置，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hc.bean
  #  以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型
      id-type: auto

      table-underline: true

      #逻辑删除配置（下面3个配置）
      logic-delete-value: -1
      logic-not-delete-value: 1
      logic-delete-field: flag

      #数据库大写下划线转换
      capital-mode: true

  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true

    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##logging:
##  level: debug